# Generated by Django 3.0.3 on 2020-06-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portofolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
