# Generated by Django 3.0.3 on 2020-07-01 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portofolio', '0002_auto_20200629_2303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Jobs',
        ),
    ]
